spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/master
    username: postgres
    password: password
  devtools:
    restart:
      enabled: true

jwt:
  secret: dGhpc0lzQVNlY3JldEtleUZvckRldmVsb3BtZW50T25seURvTm90VXNlSW5Qcm9k

frontend:
  url: http://localhost:4200

admin:
  email: admin@master.sk
  name: Admin
  password: admin123

graphhopper:
  osm:
    file: infrastructure/data/merged_sk_cz_au.osm.pbf
  graph:
    location: infrastructure/data/gh-cache